### ISSUE TITLE
Incorrect link for PowerShell plugin demo

### ISSUE THREAD

**Issue by vees** [DocusaurusCommunity/website#36]
On page 

https://docusaurus.community/plugindirectory/ 

the PowerShell plugin points to website 

hxxps://docusaurus-powershell.netlify.app/ 

which is casino site. I checked 

https://github.com/DocusaurusCommunity/website/blob/main/data/plugins/alt3.powershell.yaml which says:

`website: https://docusaurus-powershell.vercel.app/` 

So possibly the page at `plugindirecory` has not been rebuilt to match yet?

**Comment by jcubic** [comment]
@homotechsual you can close the issue.
