### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by innovortex** [DocusaurusCommunity/website#37]
Hello,

9.115 [INFO] [en] Creating an optimized production build...
9.712 [ERROR] Loading of version failed for version current
9.715 [ERROR] Error: Unable to build website for locale en.

any idea ?

**Comment by homotechsual** [comment]
Sorry, not sure what you're trying to do which has resulted in that error. To be clear this issue queue exists ONLY for issues relating to the Docusaurus.community website. It is not an avenue for support with Docusaurus in general for that please use the Docusaurus website, Discord, Subreddit or Stack Exchange.

**Comment by homotechsual** [comment]
You still haven't explained how this relates to this repository / site? Please provide enough detail to confirm it's related to this repo and to reproduce it accurately.

**Comment by homotechsual** [comment]
You're trying to do something with our website source which was never expected - you're trying to serve our community website using a Docusaurus docker image we don't control or test with. We ship our own docker file which is tested and documented on the site.
